name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.4
          elixir-version: 1.14.1
      
      - uses: actions/checkout@v3
      
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-deps-${{ hashFiles('**mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-deps-
      
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-mix-build
          restore-keys: |
            ${{ runner.os }}-mix-build
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Compile
        run: mix compile --warnings-as-errors
      
      - name: Check Formatting
        run: mix format --check-formatted
      
      - name: Run tests
        run: mix test

